#修改端口
server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web14_1?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: aq
    password: aq123456
  #配置Redis连接信息
  redis:
    host: localhost
    port: 6379
#配置mapper映射文件位置
mybatis:
  mapper-locations: classpath:mappers/*Dao.xml

#自定义配置 简单方式
studentname: hening
#自定义配置 pojo形式
citys:
  - chengdu
  - shanghai
  - shenzhen
  - beijing
students:
  - age: 18
    sex: 1
    name: aq
  - age: 17
    sex: 1
    name: hn
student:
    name: yjj
    age: 16
maps: {"name":"hatao", "age":"17"}
mysql:
  url: ${studentname}
oracle:
  url: ${studentname}